### ISSUE TITLE
How i think we can do this

### ISSUE THREAD

**Issue by WaKeMaTTa** [MustD/a3al#1]
The Arma 3 Launcher have this functionalities:
- _Addons search_ (you can search addons)
- _Download the addons_ (and automatically install this addons in arma 3 folder)
- _Allow to make package of addons._ This is very useful because in some servers you need some addons and in other server you need a others addons. If you allow to make packages you will help a lot to users.
- _Allow with 1 click launch the arma 3 with the addons selected._

---

Some tecnical things:
- The addons we can save him in github repos. And this will allow to download the addons using `git clone` and for update `git pull`

---

What do you think about my idea?

**Comment by MustD** [comment]
>  Addons search (you can search addons)
- Search where? At the moment I don't know any API or service better than Steam workshop or google.

>  Download the addons (and automatically install this addons in arma 3 folder)
- Download from where? Only thing related mod install I know, is to make simlinks for mods downloaded from Steam workshop (It is not enought to just press subscribe, you need to make simlinks in arma folder manually)

>  Allow to make package of addons. 
- Please describe your idea more detailed from technical point of view.

>   Allow with 1 click launch the arma 3 with the addons selected.
- Already implemented

>  The addons we can save him in github repos.
- Average set of mods takes ~20Gb, Not sure about ablility to have such repos for free.
